---
title: "Observaciones Tesis"
author: "Martín Vargas Estrada"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Sobre el Diseño de Investigación

La caracterización de esta investigación como "cuasiexperimental" es acertada. 


Aunque no está 100% explicitado en el texto compartido, parece bastante claro que se trata de una muestra de 44 personas sometidas a cuatro "tratamientos" o condiciones cuasi experimentales, en las que se va variando los niveles de calidad de las siguientes dimensiones del servicio culinario:

Aunque no está 100% establecido en el texto compartido, parece bastante claro que se trata de una muestra de 44 personas sometidas a cuatro "tratamientos" o condiciones cuasi experimentales, en las que se va variando los niveles de calidad de las siguientes dimensiones:


a. Producto
b. Servicio
c. Entorno Físico (Ambiente)


Estas tres dimensiones pueden concebirse como **variables  independientes**, mientras que la intención de reuso (o intención de volver a utilizar el servicio) sería la variable dependiente. 

La investigación duró cuatro semanas. 

La información recopilada durante la primera semana se utiliza como línea de base; en la segunda se expuso a los participantes a un servicio de calidad disminuida; en la tercera, a un producto de calidad inferior; por último, en la cuarta semana se sometió a los participantes a un ambiente físico de bajo nivel en comparación a los niveles de referencia iniciales.

Con cada una de estas modificaciones se intenta la manipulación cuasiexperimental de las variables independientes, una por cada semana. En este caso, la intención es crear condiciones cuasiexperimentales, en las que cada semana intenta manipular una de las variables independientes dejando las demás contantes, de tal modo de intentar medir elimpacto diferencial sobre la variable dependiente, que es la variable de interés. 

Así planteada, esta investigación seguiría un diseño cuasi experimental intrasujeto con medidas repetidas. 

### Observaciones 

1. Aunque en principio la intención es evaluar el impacto específico de cada dimensión (variable independiente) de la experiencia culinaria sobre la decisión de retorno/reuso (la variable dependiente), la realidad es que  *las variables independientes (VI) supuestamente controladas también cambian en cada semana*, es decir, no es que los participantes tengan exactamente la misma experiencia culinaria salvo en lo que corresponde a la VI que se intenta manipular. En otras palabras, *las variables independientes no están estrictamente controladas para no ser intervinientes*. 

2. Dado que la cantidad de casos es más bien pequeña, es probable que se deba apelar a herramientas estadísticas no paramétricas. Esto implica una cierta pérdida de potencia analítica, pero es posible compensarlo si se utiliza las harramientas adecuadas. 

3. Otras características de la investigación que no permiten que este sea un diseño experimental:

3.1. No existe grupo control, es decir un grupo que haya acudido al mismo restaurant al mismo tiempo que el grupo experimental sin haber sido sometido a las manipulaciones de  VI. La existencia de ese grupo permitiría conocer y eventualmente contrastar el impacto de las manipulaciones experimentales de forma integral. Por lo demás, de existir tal grupo control (idealmente, compuesto por una cantidad de personas similar a los que componen el grupo cuasiexperimental), la asignación de los participantes a uno u otro grupo (control vs experimental) debería haber sido aleatoria. 

3.2. El orden en que los participantes fueron sometidos a las diversas condiciones fue el mimso para todas las personas. En una situación experimental ideal, se debería haber variado ese orden a fin de descartar que haya algún efecto acumulativo o de acostumbramiento a las manipulaciones. A esto se le denomina "contrabalanceo". 

4. Justificación para estas características no estrictamente experimentales

En general, salvo el caso de que el jurado y/o el asesor de tesis sea muy estricto con el tema metodológico, estas "faltas al modelo experimental" están bastante justificadas; empezando por el hecho de que el mismo documento de tesis establece acertadamente que se trata de un diseño cuasi experimental. Los diseños cuasiexperimentales son perfectamente válidos dado que, como en este caso, muchas veces la vida real impide la ejecución experimental rigurosa. 

Aun así, a continuación detallo los argumentos más sólidos para subsanar estas posibles observaciones:

| Observación                                                       | Contraargumento                                                                                                                                                                    |   |   |   |
|-------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---|---|---|
| No hay grupo control                                              | No hay variables de confusión significativas previstas en la teoría que puedan ser controladas mediante un grupo de control.                                                       |   |   |   |
| La secuencia de los tratamientos es la misma para toda la muestra | Dado el tamaño muestral, usar contrabalanceo habría generado información estadísticamente poco analizable. Además, logísticamente habría sido muy desafiante.                      |   |   |   |
| Las VI no manipuladas no son constantes en cada tratamiento       | Mantener las VI no manipuladas idénticas en cada tratamiento habría introducido un elemento de "hastío" o "acostumbramiento" que probablemente habría impactado en los resultados. |   |   |   |
| Tamaño muestral relativamente pequeño                             | Si es necesario, se aplicará herramientas no paramétricas con mínima pérdida explicativa,                                                                                          |   |   |   |

## Plan de Análisis

Hay dos niveles de análisis distintos en este caso, según los objetivos y las hipótesis planteados:


1. Análisis Exploratorio: distribución (normal o no normal); medir confiabilidad (Cronbach y/o McDonald) y validez (Análisis Factorial, CFA o EFA)
1. ANOVA de Medidas Repetidas: para medir el impacto de las VI (calidad de producto, de servicio y de ambiente) sobre la intención de volver (Variable Dependiente). Para los cruces de variables indpendientes previstas en los objetivos específicos se deberá incluir análisis post-hoc.
1. Análisis de Regresión: para establecer el impacto diferencial de cada VI sobre la variable dependiente, así como, de ser factible, generar un modelo integral del proceso de decisión, así como la potencia de tal modelo (en qué medida el modelo podría explicar la decisión final). 
1. En el caso en que sea necesario, habrá que calcular las contrapartes no paramétricas de estos análisis. 
